# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define :nodo1 do |nodo1|
      nodo1.vm.box = "debian/bullseye64"
      nodo1.vm.hostname = "nodo1"
      nodo1.vm.synced_folder ".", "/vagrant", disabled: true
      nodo1.vm.provider :libvirt do |libvirt|
          libvirt.storage :file, :size => '1G'
          libvirt.storage :file, :size => '1G'
          libvirt.storage :file, :size => '1G'
          libvirt.storage :file, :size => '1G'
          libvirt.storage :file, :size => '1G'
      end
    end

  end
