# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
config.vm.define :proxy do |proxy|
    proxy.vm.box = "debian/buster64"
    proxy.vm.hostname = "proxy"
    proxy.vm.network :public_network,:bridge=>"enp2s0", use_dhcp_assigned_default_route: true
    proxy.vm.network :private_network, ip: "10.0.0.10", virtualbox__intnet: "red_privada1"
    proxy.vm.provision "shell", run: "always", inline: <<-SHELL
      sysctl -w net.ipv4.ip_forward=1
      iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -j MASQUERADE
    SHELL
  end
  config.vm.define :backend do |backend|
    backend.vm.box = "debian/buster64"
    backend.vm.hostname = "backend"
    backend.vm.network :private_network, ip: "10.0.0.11",virtualbox__intnet: "red_privada1"
    backend.vm.provision "shell", run: "always", inline: <<-SHELL
        ip r del default
        ip r add default via 10.0.0.10
	apt update && apt upgrade -y
	apt install docker.io -y
	docker run -d --name some-nextcloud -p 8080:80 nextcloud
	docker run -d --name some-ghost -p 8081:2368 ghost
    SHELL
  end
  
end
