# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.hostname = "test"
  config.vm.hostname = "mimaquina"
  config.vm.network :private_network, ip: "172.22.200.100"
end
