# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
config.vm.define :balanceador do |balanceador|
    balanceador.vm.box = "debian/buster64"
    balanceador.vm.hostname = "balanceador"
    balanceador.vm.network :public_network,:bridge=>"enp2s0", use_dhcp_assigned_default_route: true
    balanceador.vm.network :private_network, ip: "10.10.10.1", virtualbox__intnet: "red_privada1"
    balanceador.vm.provision "shell", run: "always", inline: <<-SHELL
      sysctl -w net.ipv4.ip_forward=1
      iptables -t nat -A POSTROUTING -s 10.10.10.0/24 -j MASQUERADE
    SHELL
  end
  config.vm.define :apache1 do |apache1|
    apache1.vm.box = "debian/buster64"
    apache1.vm.hostname = "apache1"
    apache1.vm.network :private_network, ip: "10.10.10.11",virtualbox__intnet: "red_privada1"
    apache1.vm.provision "shell", run: "always", inline: <<-SHELL
        ip r del default
        ip r add default via 10.10.10.1
	      apt update && apt upgrade -y
	      apt install apache2 php7.3 libapache2-mod-php7.3 -y
        cp /vagrant/index1.html /var/www/html/index.html
        cp /vagrant/sesion.php /var/www/html/
    SHELL
  end

  config.vm.define :apache2 do |apache2|
    apache2.vm.box = "debian/buster64"
    apache2.vm.hostname = "apache2"
    apache2.vm.network :private_network, ip: "10.10.10.22",virtualbox__intnet: "red_privada1"
    apache2.vm.provision "shell", run: "always", inline: <<-SHELL
        ip r del default
        ip r add default via 10.10.10.1
	      apt update && apt upgrade -y
	      apt install apache2 php7.3 libapache2-mod-php7.3 -y
        cp /vagrant/index2.html /var/www/html/index.html
        cp /vagrant/sesion.php /var/www/html/
  
	  SHELL
  end
  
end
